name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DTinyArray_BuildTests=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        working-directory: ${{github.workspace}}/build/tests
        run: ctest

      - name: Build examples
        run: | 
          cmake -S ${{github.workspace}}/examples -B ${{github.workspace}/build-examples
          cmake --build ${{github.workspace}}/build-examples

      - name: Run examples
        run: |
          ${{github.workspace}}/build-examples/cmake-usage/tiny_array_examples_cmake_usage
